# Experiment Parameters
root_dir: /mnt/projects/debruinz_project/integration/tensorboard
experiment_name: snakemake_testing
run_name: run1

config_name: config.yaml

ckpt_path: checkpoints/last.ckpt




# ENVIROMENT SPECIFIC
module_path: /mnt/projects/debruinz_project/denhofja/sciml/src
env_path: '/mnt/projects/debruinz_project/pytorch-nightly-env/bin/python3'
