# Experiment Parameters
root_dir: tensorboard
experiment_name: experiment
run_name: run

config_name: config.yaml

ckpt_path: checkpoints/last.ckpt


# ENVIROMENT SPECIFIC
module_path: /mnt/projects/debruinz_project/denhofja/sciml/src
env_path: '/mnt/projects/debruinz_project/pytorch-nightly-env/bin/python3'
